<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dre Simmons">
<meta name="dcterms.date" content="2025-11-06">

<title>Week 3 Deliverable - RWARE tiny-4ag-hard-v2 with QMIX: Parallel Learning Experiment and Comparative Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="W3D_Simmons_files/libs/clipboard/clipboard.min.js"></script>
<script src="W3D_Simmons_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="W3D_Simmons_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="W3D_Simmons_files/libs/quarto-html/popper.min.js"></script>
<script src="W3D_Simmons_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="W3D_Simmons_files/libs/quarto-html/anchor.min.js"></script>
<link href="W3D_Simmons_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="W3D_Simmons_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="W3D_Simmons_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="W3D_Simmons_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="W3D_Simmons_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 3 Deliverable - RWARE tiny-4ag-hard-v2 with QMIX: Parallel Learning Experiment and Comparative Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dre Simmons </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 6, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1">
<h1>Executive Summary</h1>
<p>This report documents the methodology and results of QMIX applied to the RWARE <code>tiny-4ag-hard-v2</code> warehouse task, comparing outcomes and challenges to last week’s (Week 2) baseline setup. The goal is to see the effect of parallelization and increased coordination complexity on multi-agent learning performance.</p>
<hr>
</section>
<section id="experimental-workflow" class="level1">
<h1>Experimental Workflow</h1>
<section id="environment-and-tool-setup" class="level2">
<h2 class="anchored" data-anchor-id="environment-and-tool-setup">Environment and Tool Setup</h2>
<p><strong>Platform:</strong> Mac (M3, 16GB RAM), Python venv<br>
<strong>Libraries:</strong> gymnasium, rware, torch, tensorboard <em>(was not working for unknown reasons)</em>, EPyMARL<br>
<strong>Task Configuration:</strong> RWARE <code>tiny-4ag-hard-v2</code> (four agents, two shelves), “parallel” protocol instead of “episode”</p>
</section>
<section id="treatment-design" class="level2">
<h2 class="anchored" data-anchor-id="treatment-design">Treatment Design</h2>
<p><strong>Initial (Parallel, Baseline Config):</strong> Implemented parallel environment sampling with default parameters (the parameters that led to a successful run from Week 2).<br>
<strong>Secondary (Parallel, Aggressive Config):</strong> Increased buffer, prolonged exploration decay, tuned rollout hyperparameters.<br>
<strong>Comparison:</strong> Week 2 baseline (episode setup, two agents, one shelf)</p>
<hr>
</section>
</section>
<section id="configuration-evolution-switching-from-effective-episode-qmix-to-parallel-qmix" class="level1">
<h1>Configuration Evolution: Switching from Effective Episode QMIX to Parallel QMIX</h1>
<p>This week focused on two main parallel configurations to address the increased difficulty of RWARE <code>tiny-4ag-hard-v2</code> (4 agents, 2 shelves) and compare their impact. The decision was not to scale to a larger warehouse to see the effect of four agents coordinating in the same environment as Week 2.</p>
<hr>
<section id="initial-parallel-training-configuration" class="level2">
<h2 class="anchored" data-anchor-id="initial-parallel-training-configuration">Initial Parallel Training Configuration</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 17%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
<th>Purpose / Why Important</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>runner</td>
<td>parallel</td>
<td>Runs multiple environments to speed up experience collection.</td>
</tr>
<tr class="even">
<td>batch_size_run</td>
<td>8</td>
<td>Number of parallel environments running simultaneously.</td>
</tr>
<tr class="odd">
<td>batch_size</td>
<td>256</td>
<td>Number of samples per update. Larger batches stabilize learning but require more memory; balance learning speed and stability.</td>
</tr>
<tr class="even">
<td>buffer_size</td>
<td>200,000</td>
<td>Maximum number of experiences; larger buffer increases sample diversity and long-term learning in sparse tasks.</td>
</tr>
<tr class="odd">
<td>epsilon_start</td>
<td>1.0</td>
<td>Maximizes early exploration.</td>
</tr>
<tr class="even">
<td>epsilon_finish</td>
<td>0.1</td>
<td>Allows mostly greedy exploitation by end of training.</td>
</tr>
<tr class="odd">
<td>epsilon_anneal_time</td>
<td>5,000,000</td>
<td>Number of steps for epsilon to decay; longer value allows thorough policy learning.</td>
</tr>
<tr class="even">
<td>t_max</td>
<td>20,000,000</td>
<td>Standard training duration for initial testing.</td>
</tr>
<tr class="odd">
<td>gamma</td>
<td>0.99</td>
<td>Standard RL discount factor.</td>
</tr>
<tr class="even">
<td>lr</td>
<td>0.0005</td>
<td>Stable learning rate for consistent training.</td>
</tr>
<tr class="odd">
<td>mixer</td>
<td>qmix</td>
<td>Essential for cooperative agent mixing.</td>
</tr>
<tr class="even">
<td>agent</td>
<td>rnn</td>
<td>Handles partial observability in MARL.</td>
</tr>
<tr class="odd">
<td>env_args (key)</td>
<td>rware:rware-tiny-4ag-hard-v2</td>
<td>Defines the experiment environment.</td>
</tr>
<tr class="even">
<td>env_args (time_limit)</td>
<td>100</td>
<td>Maximum steps per episode.</td>
</tr>
<tr class="odd">
<td>save_model</td>
<td>True</td>
<td>Checkpoints enabled for reproducibility and recovery.</td>
</tr>
</tbody>
</table>
<section id="key-points" class="level3">
<h3 class="anchored" data-anchor-id="key-points">Key Points</h3>
<ul>
<li>Parallel runner and batch_size_run enable fast, varied sample collection.<br>
</li>
<li>Large buffer and batch size promote stable, diverse learning for difficult, multi-agent tasks.<br>
</li>
<li>Slow annealing (epsilon_anneal_time) and retained exploration (epsilon_finish) help agents reliably find sparse rewards.<br>
</li>
<li>Saving model checkpoints protects against failure and helps analyze training progress.</li>
</ul>
<p><strong>Result:</strong><br>
Agents began to learn, achieving a final return mean of <strong>2.58</strong> and target mean of <strong>8.21</strong>, approaching solved status under parallel config. Week 2’s benchmark was a return mean above 2.5.</p>
<hr>
</section>
</section>
<section id="secondary-aggressive-parallel-configuration" class="level2">
<h2 class="anchored" data-anchor-id="secondary-aggressive-parallel-configuration">Secondary (Aggressive) Parallel Configuration</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 17%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
<th>Purpose / Why Important</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>runner</td>
<td>parallel</td>
<td>Same as above.</td>
</tr>
<tr class="even">
<td>batch_size_run</td>
<td>16</td>
<td>Increased to create more parallel instances.</td>
</tr>
<tr class="odd">
<td>batch_size</td>
<td>512</td>
<td>Further increased; promotes stable multi-agent updates.</td>
</tr>
<tr class="even">
<td>buffer_size</td>
<td>200,000</td>
<td>Larger buffer, critical for diverse experience replay.</td>
</tr>
<tr class="odd">
<td>epsilon_start</td>
<td>1.0</td>
<td>Full exploration at start.</td>
</tr>
<tr class="even">
<td>epsilon_finish</td>
<td>0.10</td>
<td>Slightly more exploration retained at end.</td>
</tr>
<tr class="odd">
<td>epsilon_anneal_time</td>
<td>1,000,000</td>
<td>Quicker shift from exploration to exploitation.</td>
</tr>
<tr class="even">
<td>t_max</td>
<td>20,000,000</td>
<td>Longer training horizon for sparse-reward setting.</td>
</tr>
<tr class="odd">
<td>gamma</td>
<td>0.99</td>
<td>Standard RL setup.</td>
</tr>
<tr class="even">
<td>lr</td>
<td>0.001</td>
<td>Higher learning rate for quicker updates (monitor for stability).</td>
</tr>
<tr class="odd">
<td>mixer</td>
<td>qmix</td>
<td>Cooperative value mixing continues.</td>
</tr>
<tr class="even">
<td>agent</td>
<td>rnn</td>
<td>Same as above.</td>
</tr>
<tr class="odd">
<td>env_args (key)</td>
<td>rware:rware-tiny-4ag-hard-v2</td>
<td>Same task environment.</td>
</tr>
<tr class="even">
<td>env_args (time_limit)</td>
<td>100</td>
<td>Consistent episode bound.</td>
</tr>
<tr class="odd">
<td>save_model</td>
<td>True</td>
<td>Checkpoints enabled for reproducibility and recovery.</td>
</tr>
</tbody>
</table>
<section id="key-points-1" class="level3">
<h3 class="anchored" data-anchor-id="key-points-1">Key Points</h3>
<ul>
<li>Doubling batch_size_run and batch_size increases sample and training throughput—most effective for systems with more compute resources.<br>
</li>
<li>Faster epsilon annealing means agents start exploiting quicker, which can speed learning but may risk premature convergence in sparse environments.<br>
</li>
<li>Higher learning rate speeds up model updates; requires monitoring for stability.<br>
</li>
<li>Large buffer and model checkpoints protect learning stability and enable analysis/recovery.</li>
</ul>
<p><strong>Result:</strong><br>
Agents showed stronger learning, reaching a final return mean of <strong>1.67</strong> and target mean of <strong>8.95</strong> (with a more stable plateau), indicating improved exploration, sample efficiency, and stability.</p>
<hr>
</section>
</section>
</section>
<section id="why-the-improvements-worked" class="level1">
<h1>Why the Improvements Worked</h1>
<p>Parallel rollout combined with longer exploration, bigger buffers, and larger batches enabled robust learning in high-coordination, sparse-reward MARL tasks.<br>
Checkpointing allowed for confident evaluation and repeatability.</p>
<hr>
</section>
<section id="main-metrics-results" class="level1">
<h1>Main Metrics &amp; Results</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Week &amp; Treatment</th>
<th>Agents</th>
<th>Shelves</th>
<th>Target Mean (final)</th>
<th>Return Mean (final)</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Week 2 (Episode)</td>
<td>2</td>
<td>1</td>
<td>3.25</td>
<td>3.25</td>
<td>Solved</td>
</tr>
<tr class="even">
<td>Week 3 Initial (Parallel)</td>
<td>4</td>
<td>2</td>
<td>8.21</td>
<td>2.58</td>
<td>Near solved</td>
</tr>
<tr class="odd">
<td>Week 3 Secondary</td>
<td>4</td>
<td>2</td>
<td>8.95</td>
<td>1.67</td>
<td>Strong learning</td>
</tr>
</tbody>
</table>
<p>Increasing agent and shelf count made the environment harder, requiring more sample diversity and longer exploration to approach optimal learning.<br>
Parallel enabled better sample efficiency compared to episode-based Week 2 training.</p>
<p><strong>QUICK NOTE:</strong> Interpreting <code>Return Mean</code> vs.&nbsp;<code>Target Mean</code> in This Experiment Although the secondary (aggressive) parallel run produced a higher target mean (8.95) than the initial parallel run (8.21), its return mean was actually lower (1.67 versus 2.58). This demonstrates a common scenario in deep multi-agent RL: the average Q-value targets used for learning (target mean) can be inflated (or more optimistic) during aggressive or unstable training, while the actual episode returns (return mean) show the true effectiveness of the policy in the environment.</p>
<p>Return mean is the main measure of practical agent performance—how much reward the agents truly achieved. Target mean is an internal metric reflecting the values predicted and bootstrapped by the neural network during training; these can run higher or show more volatility, but do not always translate into better real-world behavior.​</p>
<p>In literature, discrepancies like this are often caused by fast learning rates or aggressive parameter settings, which may lead to value overestimation or oscillation. As shown, the initial parallel config ultimately delivered better real-world agent returns, so it represents more robust performance this week.​</p>
<p><em>Key Takeaway:</em></p>
<p>Always prioritize return mean for evaluating agent success.</p>
<p>Target mean is best used to monitor learning stability and the relative scale of Q-value predictions, but should not be the sole measure of policy quality.</p>
<p>If the metrics diverge, the config aggressiveness may cause optimism in value updates without corresponding gains in episode rewards.</p>
<hr>
</section>
<section id="learning-curves-visuals" class="level1">
<h1>Learning Curves &amp; Visuals</h1>
<p>No visuals to display due to TensorBoard issue. Relied on quantitative metrics above that were produced as JSON files.</p>
<hr>
</section>
<section id="changes-from-week-2" class="level1">
<h1>Changes from Week 2</h1>
<ul>
<li>Shift from episode-based to parallel rollouts.<br>
</li>
<li>Larger team size and coordination complexity.<br>
</li>
<li>Aggressive config tuning (buffer size, batch, and epsilon scheduling) was essential for good results.</li>
</ul>
<hr>
</section>
<section id="practical-takeaways" class="level1">
<h1>Practical Takeaways</h1>
<ul>
<li>Parallel QMIX supports robust multi-agent learning even as coordination difficulty increases.<br>
</li>
<li>Buffer size and exploration schedule must be scaled with environment complexity.<br>
</li>
<li>Comparative metrics show QMIX remains adaptable across sampling protocols, but tuning is crucial as task demands grow.</li>
</ul>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li>Rashid, T., Samvelyan, M., De Witt, C.S., Farquhar, G., Foerster, J., &amp; Whiteson, S. (2018). <em>QMIX: Monotonic Value Function Factorisation for Deep Multi-Agent Reinforcement Learning.</em> Proceedings of the 35th International Conference on Machine Learning (ICML), 2018.<br>
</li>
<li>Papoudakis, G., Christianos, F., Schäfer, L., &amp; Albrecht, S.V. (2021). <em>Benchmarking Multi-Agent Deep Reinforcement Learning Algorithms in Cooperative Tasks.</em> NeurIPS, 2021.<br>
</li>
<li>Farama Foundation. <em>RWARE: Multi-Agent Warehouse Environment.</em> https://github.com/Farama-Foundation/RWARE<br>
</li>
<li>EPyMARL: <em>Extended PyMARL Framework.</em> https://github.com/oxwhirl/epymarl<br>
</li>
<li>DI-engine documentation: <em>QMIX.</em> https://di-engine-docs.readthedocs.io/en/latest/12_policies/qmix.html<br>
</li>
<li>Schaefer, L. (2021). <em>Efficient Exploration in Single-Agent &amp; Multi-Agent Deep RL.</em> PhD Thesis, TU Darmstadt. https://www.lukaschaefer.com/files/phd_thesis.pdf<br>
</li>
<li>SMAClite: <em>Multi-agent Environments.</em> https://openreview.net/pdf/9b76af423d461f3f4e700735a1d1ec87fa251db3.pdf</li>
<li>ChatGPT. Portions of this report were formatted with assistance from ChatGPT</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>